services:
  app:
    build: .
    volumes:
      - ./var/logs:/app/apps/backend/logger/var/log
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timer
      - MYSQL_USER=timer
      - MYSQL_PASSWORD=root
    volumes:
      - ./var/db:/var/lib/mysql
      - ./init/db/mysql:/utils/init
    healthcheck:
      test: chmod +x /utils/init/healthcheck.sh && sh /utils/init/healthcheck.sh
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

